env:
  browser: true
  es6: true
  jest/globals: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  it: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules:
  no-console: warn
  no-unused-vars:
    - error
    - varsIgnorePattern: "(React*|App)"

